### ISSUE TITLE
docker image is not upto date with firebase-tools version

### ISSUE THREAD

**Issue by Praggie** [nohitme/docker-hugo-firebase#3]
Hi,

         Your docker image is not upto date with firebase-tools. it is failing the deployment with HTTP-STATUS code 410. It seems you may need to rebuild the new docker image with latest firebase cli tools.

Regards

**Comment by nohitme** [comment]
thank you guys for reporting issue and creating PR!

Let me test with my site locally first and I will take the PR. (will do this by EOD)
